<?php
$sql = "CREATE TABLE User_UR(
User_Name VARCHAR(10) NOT NULL,
User_Id VARCHAR(20) NOT NULL,
User_Pwd VARCHAR(256) NOT NULL,
User_PhoneNum INT NOT NULL,
User_Addr VARCHAR(256) NOT NULL,
User_SignDate DATETIME NOT NULL,
PRIMARY KEY (User_Id)
);"
?>
